### PR TITLE
Fix deprecated gen function

### PR DESCRIPTION
**Pull request by Ladsgroup**
Fix https://bugs.revi.xyz/T326

### CODE REVIEW

**Comment by Ladsgroup** [comment]
Untested

**Comment by revi** [comment]
```
Traceback (most recent call last):
  File "pwb/pwb.py", line 420, in <module>
    if not main():
  File "pwb/pwb.py", line 412, in main
    run_python_file(filename,
  File "pwb/pwb.py", line 112, in run_python_file
    exec(compile(source, filename, 'exec', dont_inherit=True),
  File "rfcbot.py", line 60
    .getReferences(only_template_inclusion=True)
IndentationError: unexpected indent
CRITICAL: Exiting due to uncaught exception <class 'IndentationError'>
```

pwb repo at `commit aa0dd58cf0d641e6afa19183159c19a2c728b230 (HEAD -> master, origin/stable)`

**Comment by Ladsgroup** [comment]
ugh. fixed.

**Comment by revi** [comment]
```
WARNING: rfcbot.py:77: FutureWarning: comment argument of pywikibot.page.BasePage.put is deprecated; use summary instead.
  templatepage.put(
```

But it works for now :tm: so merging. Will think about it later when it breaks :tm:.

**Pull request merged**
